### ISSUE TITLE
Missing `original_url` for migrated repos

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/gitea#15]
The response for `GET repos/{owner}/{repo}` has the `original_url: ''`, I don't remember if this was always the case or not.

**Comment by kasbah** [comment]
Probably an upstream issue, no?

**Comment by AbdulrhmnGhanem** [comment]
No, I just tried it on try.gitea.io and it works fine.

**Comment by kasbah** [comment]
I see, remember we are probably behind what's deployed to gitea.io though. Maybe try and merge upstream and see if it resolves it.

**Comment by AbdulrhmnGhanem** [comment]
Closed via #18.
