### ISSUE TITLE
Configure CORS for non repository routes

### ISSUE THREAD

**Issue by AbdulrhmnGhanem** [kitspace/gitea#6]
The options [here](https://docs.gitea.io/en-us/config-cheat-sheet/#cors-cors) for configuring CORS doesn't support the `Access-Control-Allow-Origin` option.
With this configuration in the `app.ini` file: 
```.ini
[cors]
ENABLED=true
SCHEME=http
ALLOW_DOMAIN=kitspace.test,staging.kitspace.org,kitspace.org
ALLOW_SUBDOMAIN=true
METHODS=POST
MAX_AGE=10m
ALLOW_CREDENTIALS=true
```
The headers of the response are: 
```
Access-Control-Allow-Headers
Access-Control-Allow-Methods: POST
Access-Control-Max-Age: 600
Connection: keep-alive
Content-Length: 70
Content-Type: application/json; charset=utf-8
Date: Sat, 29 Aug 2020 15:36:17 GMT
Server: nginx/1.17.6
X-Csrf-Token: 4CSnVuWtSzUdNcnrHZATVY8142c6MTU5ODY0MTQ4Njc5MTMxNzMzMw
X-Frame-Options: SAMEORIGIN
``` 
And the request from the browser results in the same CORS error.
There's an `ACCESS_CONTROL_ALLOW_ORIGIN ` option under the `[repository]` configuration but no other occurrences in the whole Gitea codebase.

**Comment by AbdulrhmnGhanem** [comment]
To make things more complicated it has nothing to do with Gitea itself; it's a limitation of the [library](https://github.com/go-macaron/cors/blob/b0274f40d4c7e4541b5b41e24b590abb9e5d5b21/cors.go#L86) used by Gitea to handle requests(maybe a design decision).

Some relevant [disscusion](https://github.com/go-gitea/gitea/issues/7840#issuecomment-524498491).

**Comment by kasbah** [comment]
I don't have time to look closer at this right now, but it makes me think we will have to proxy these endpoints to the main domain via Nginx or modify the header of the requests in Nginx.

**Comment by kasbah** [comment]
It seems another option is to fork to cors module and make it do what we want.

**Comment by AbdulrhmnGhanem** [comment]
> It seems another option is to fork to cors module and make it do what we want.

Or we can drop Gitea altogether :rofl: :rofl: :rofl:

Anyways look at the new PR, especially the latest commits.

**Comment by kasbah** [comment]
What's the status of this?

**Comment by AbdulrhmnGhanem** [comment]
Fixed it by configuring Nginx https://github.com/kitspace/gitea/pull/7#issuecomment-685651252
